In [1]:
#Numpy
from array import array 

In [2]:
arr = array ('i', [1,2,3])
type(arr)

array.array

In [3]:
%pip install numpy


     ---------------------------------------- 0.0/59.7 kB ? eta -:--:--
     ------ --------------------------------- 10.2/59.7 kB ? eta -:--:--
     ------------- ------------------------ 20.5/59.7 kB 217.9 kB/s eta 0:00:01
     -------------------------- ----------- 41.0/59.7 kB 279.3 kB/s eta 0:00:01
     -------------------------------------- 59.7/59.7 kB 287.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.9 MB 1.7 MB/s eta 0:00:08
   ---------------------------------------- 0.1/12.9 MB 1.4 MB/s eta 0:00:09
    --------------------------------------- 0.3/12.9 MB 1.7 MB/s eta 0:00:08
   - -------------------------------------- 0.5/12.9 MB 2.6 MB/s eta 0:00:05
   -- ------------------------------------- 0.7/12.9 MB 3.1 MB/s eta 0:00:04
   -- ------------------------------------- 0.8/12.9 MB 3.4 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/12.9 MB 3.9 MB/s eta 0:00:03
   ---


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: C:\Users\isabe\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [5]:
#Vetor linha 
arr = np.array ([1,2,3,4])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(4,)

In [10]:
#Vetor coluna 
arr_2 = np.array([[1],[2],[3],[4]])
print(arr_2)

[[1]
 [2]
 [3]
 [4]]


In [11]:
matriz = np.array([[1,2,3,4],[2,1,3,4],[3,5,4,6],[4,5,8,9]])
print(matriz)

[[1 2 3 4]
 [2 1 3 4]
 [3 5 4 6]
 [4 5 8 9]]
